### ISSUE TITLE
Negative Cashflow selling ViPC in Online Shop Platform?

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#1]
# The Problem
## Online Shop Platform

An Online Shop Platform is a service that provides the Online Shop Infrastructure and lets you open a virtual Online Shop within their platform. Examples are:
- Amazon
- Newegg
- eBay
- Taobao
## Our intended Cash-Flow
1. Customer buys and pays ViPC in V²Amazon Shop
2. Amazon releases funds
3. Shop uses funds to buy part in other Amazon Shops
4. Parts arrive. Shop assembles parts to ViPC.
5. Shop ships ViPC to buyer.
6. Buyer received the PC and is happy.
## Amazon Cash-Flow in Real Life

![](http://www.eigener-online-shop.net/wp-content/uploads/amazon-shop-eroeffnen.png)
1. Customer buys and pays ViPC in V²Amazon Shop
2. Amazon releases funds **after** shop ships to buyer
1. Money may need 3 ... 5 days to show in your Bank account
## eBay Cash Flow in Real Life
1. Customer buys and pays ViPC in eBay Shop
2. eBay releases funds **after** shop ships to buyer
   1. Money may need 3 ... 5 days to show in your Bank account
## Taobao Cash Flow in Real Life
1. Customer buys and pays ViPC in Taobao Shop
2. Shop Ships to customer
3. Customer receives shipment. Customer has 7 day time to release funds
4. After funds are releases they show up instantly on Alipay
## Catch 22 Problem
- Shop can only ship after releases funds, as we need funds to buy parts for ViPC
- Online Shop Service Provider will only release funds after shop ships
# Proposed Solutions
## Selling ViCase on Online Shop still possible

You would have ViCase in stock. Customer buys and pays. You can ship same or next day. After you ship you can request Amazon to pay. You can release of funds same day.
## Selling ViCase Assembly service on Online Shop

Also still possible. It is a $100 Item. Terms are that the customer uses the Configurator to assemble his custom PC. Then he uses the Configurator to order the items in Amazon, shipping address to you. You receive parts, assemble ViCase PC and ship to customer. Once you have shipped you can get amazon to release $100 same day to you.
## Newegg Combo Deals

→ #3 
## Selling of ViPC on Online Shop Service requires negative cash flow

Example: Say you sell 3 ViPC in 3 days, each for $1000. Then you would need to finance $3,000 to buy the parts for ViPC, then ship to customer. It takes about 2 days for parts to arrive, 1 day to build and test. Maybe can start slow, build cash flow? 
## All Online Services are the same

We checked: Amazon, eBay, Taobao. They all present the same Catch 22 problem to our original idea on how we can sell completely assembled PCs.
## Build our own online shop (later)

We have built a working shop from which we sold ViDock. We certainly can do it again. But then Nino and Bobby would need to build their own shop. My instinct says this is not the right time. The VirtueMart shop in Joomla took a lot of maintenance time. We need to find a more maintenance free shop solution. Right now our focus must be to make ViCase and ViPC ready and sell it. Not to build better sales tools.
# Reference
## Getting Paid in Amazon
- [Amazon►Getting Paid](https://www.amazon.com/gp/help/customer/display.html?nodeId=1161250)
- [Amazon►Transfers to Your Bank Account](https://www.amazon.com/gp/help/customer/display.html?&nodeId=3485851)
- [Amazon-DE►FAQ Verkauf](https://services.amazon.de/programme/online-verkaufen/faq.html)
  ## Related Issues
- #2 
- #3
# Proposed Conclusion
- **Problem:** All evaluated Online Shop Platforms will require negative cash-flow to sell finished ViPC. That is you need to finance the time between customer paid Amazon and you ship the ViPC
- **Solution:** In #4 ViPC Commerce Options we show how to overcome this problem with 5 different solutions.
# Tasks
- [x] NR: Report Problem to HC
- [x] HC: Create issue on the matter
- [x] HC: Make initial research. Is Nino's claim correct → It is correct! See the [Getting Paid in Amazon](#getting-paid-in-amazon) in Reference
- [x] @bcaswelch Write a comment when you get paid in eBay? → After shop ships.
- [x] @bcaswelch Write a comment on your thoughts how to proceed. Better initiate conference call on skype → #2 & #3
- [ ] Nino: Discuss with HC this updated issue. Do you agree on the conclusion?

**Comment by bcaswelch** [comment]
R&U

**Comment by VillageHubertChen** [comment]
# Additional Proposal to solve Cash Flow: Credit

The idea is to get a line of credit from the bank with the paid order on amazon as security to the Bank. In general this would require that have your Bank account for a while and you have a good relationship with your account manager. 

Technically the funds of money paid by your shop customer to Amazon can only be released to your Bank account. So this can be considered kind of security from your Bank's perspective. On the other hand these funds can be a lot and after you ship can be $0. So you Bank would need to constantly adjust your credit line. Also how can your Bank see these funds?

# Tasks
- [ ] Nino: Would you be willing to use credit to buy parts for your paid customer's order? If so, would your Bank give you a line of credit?
- [ ] Nino: Research if this is a common problem of catch 22 and if there are known solutions to it?
- [x] @bcaswelch : Would you be willing to use credit to buy parts for your paid customer's order? If so, would your Bank give you a line of credit? → It may be possible. Need to talk with my parent. But it is not a preferred solution as the risk is much higher, and to compensate for it we must charge a higher assembly fee, which would be misunderstood in the community. I prefer to go for → #3

**Comment by VillageHubertChen** [comment]
# Meeting with Bobby
1. HC found that all Online Shops have same payment schedule → Receive money only after shipment
2. Bobby find a great new option → #3 
3. Bobby actually likes Assembly Service over Selling Finished PC. Believes that you can sell this story better than run of the mill PC / get the word out

**Comment by bcaswelch** [comment]
Parents are visiting next weekend so I'll get back to you about the possibility of negative cash flow. I think amazon/newegg is a great option/good for advertising, but would like to see how a custom shop works before shelling out several thousand dollars.

**Comment by VillageHubertChen** [comment]
Agreed. But also lets continue to cultivate multiple options. If we choose to make our first shop with Joomla and Virtue Mart again, it will not be time efficient to set up such a shop for you. There will also be the option that Andrew might build a different solution based on Wordpress that is easier to manage. There are too many variables at this moment to see which one will be available first.

Remember that you always can limit your cash exposure on Amazon by only having 1 piece in stock, so you do not need to shell out several thousand dollars. After several sales were successful, you may be more comfortable to increase stock to 2 pcs, then 3, then more ...
