### ISSUE TITLE
Milestones v4

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#10]
# Reference
- [V²Site►Home](http://v-squared.github.io/)
# Revisions History
## v1
- Initial release
- Focused on ViPC as initial main source of funding for V² Initiative by sales via Amazon
## v2
- Rewritten after we learned about Negative Cash Flow of selling ViPC in Amazon → #1 
- ViPC remains our long term strategy to provide funding of V² Initiative
- Initial Funding however is now provided by ViCase Pre-Orders → #6 
- Community engagement is rewarded via Discounts, Stretch Goal Bonus & Referral Bonus → #5 
## v3
- Optimized timing based on Michael's feedback
- Added Computex Taipei
- Optimized timing based on Xiao Mao's feedback
- Linked Milestones to months: March is now M03 instead M01
  - shortened Milestone title, as month no longer need to be listed
  - (I reassigned all milestones to all Issues accordingly) 
- Cleaner Big Picture Launch Sequence:
  - 1) Restructured 2) Simplified 3) Shortened 
  - Split monthly milestones into 1) Highlights 2) Details
- New cleaned up monthly Milestone Titles:
  - M03: Launch V²Site / Sample Production
  - M04: Launch ViSite / Launch Community Pre-Order
  - M05: Ship Pre-Order / Push Pre-Order Marketing
  - M06: Computex, Launch ViPC & V²Community Store
  - M07: Expand: Marketing & Sales & Production
## v4
- rewrite to match the new campaign approach, as described in → #15  
  - **Q2:** Community Campaign
  - **Q3:** Shops & Press Campaign
  - **Q4:** OEM Campaign
### Home Page: OEM Campaign
# M03: Launch V²Site / Sample Production
## Highlights
- **Launch V²Site:** Home Page, Site Structure, Community Collaboration, V²PC
- **ViSite Content:** ( ViCase & ViPC ) \* ( Models | Features | Use )
- **Start Samples Pre-Production:** ViCase Mini, V²Panel, V²Surge
## Details
- [x] Case: ViCase Mini Sample: Change design for Pre-Production, Find Factory, Get Quote, Create CAM files, Create CAM workflow docu, Release to Factory
- [x] PCB Tech: Switch from proprietary Schematic + PCB + CAD to FOSS: KiCAD + FreeCAD
- [ ] PCB: V²Panel: Schematic, Review, PCB Design, Review
- [ ] PCB: V²Surge: Schematic, Review, PCB Design, Review
- [ ] PCB: Panel Form for V²Panle + V²Surge. Tape Out. Put to production. 
- [x] Make: Secure Production Resources
- [x] V²Site: Tech Prototype: 1) gh-pages 2) Jekyll 3) Cloud9 4) GitHub 5) uikit
- [x] V²Site: Testing on different OS, different Browsers (using Cloud9 IDE)
- [ ] V²Site: V² Home Page: 1) Create Structure 2) Tells story V² 3) Site Navigation 
- [ ] V²Site: 1) Restructure GitHub Repositories 2) Wiki Pages to Code 3) Switch to Jekyll
- [ ] V²Site: V²PC (Configurations with ready shopping lists to Amazon & Newegg)
- [ ] V²Site: Trailblazer Products (Collaborative development of ViSite's Content)
- [ ] V²Site: Complete the section: "Corporation"
- [ ] Shops: Determine estimated Costs: (Shipping, Tax, Logistics, Service Fees)
- [ ] Shops: Getting ready to be used: Amazon: US, D & eBay: HK, AU, SG
- [ ] Shops: Building Amazon US Hero Shop
- [ ] V²Art: 1) Workflow, 2) Repo 3) New ViCase Models Rendered Photos 4) Collaboration
- [ ] V²Art: Home Page Illustrations
- [ ] V²Art: ViCase Illustrations
- [x] Community: Create Milestones (This document)
- [x] Community: Move to vote on Licensing: → Change to CC + MIT. Logo License separate.
- [ ] Community: Leading via Mission, True North, Stages & Milestones
- [x] Community: Management via Issues (derived from Milestones) on V²Site
- [ ] Community: Contribution via Pull Requests on V²Site
- [ ] Community: Activate: Facebook, Twitter by announcing V²
- [ ] Community: Joint develop V²PC, V²Community Shops
# M04: Launch ViSite / Community Pre-Order
## Highlights
- **Launch ViSite:** Fully functional Web Site with Product Pages, Support and Online Shop show casing ViCase & ViPC on www.villagetronic.com 
- **Begin Pre-Sales:** Community Promotions of Pre-Orders. Two types: 1) Gamma Samples Ship in May, but are more expensive 2) Pre-Order are with discount, ship in June 
- **BTL Pre-Production:** Receive Sample and Bring to Life.
- **ViCase Community Pre-Order Marketing:** It is like a campaign. Only we are already in production. If we reach pre-order target we give away bonus, such as free Arduino.
## Details
- [ ] Case: IQC Samples of ViCase Mini, Assemble Case, Compile ECR List
- [ ] Case: Build complete ViPC with ViCase
- [ ] Case: _Review-Sample Production:_ Include our ECR, Include factory's ECR, Add double sided cutting, Get Quote, Create CAM files, Create CAM workflow docu, Release to Factory
- [ ] Case: _Review-Samples:_ Send to V²Community Shops / Reviewers
- [ ] PCB: V²Panel: Build 1 pcs first. Bring to Life. Write ECR List. 
- [ ] PCB: V²Panel: Assemble for Review Samples.
- [ ] PCB: V²Surge: Build 1 pcs first. Bring to Life. Write ECR List. Assemble for Review Samples.
- [ ] PCB: V²Surge: Assemble for Review Samples.
- [ ] ViSite: Move "Trailblazer Products" Pages to ViSite
- [ ] ViSite: Turn on Shop on ViSite. Put all Products in. Pre-Sales Products ready to order.
- [ ] ViSite: Turn on Support again. Bind it into site. Assign people with allocated time to answer
- [ ] Shops: Determine exact Costs: (Shipping, Tax, Logistics, Service Fees)
- [ ] Shops: Referral Bonus Program → #5 / determine qty of Review Samples
- [ ] V²Art: Photography: Stills & Video
- [ ] V²Art: Photo Rendering: Create shot list, rendering, processing, updating to pages
- [ ] V²Art: Processing of Images & Publishing Photos
- [ ] V²Art: Edit a better than nothing ViCase Pitch Video
- [ ] V²Site: Complete the section: "For Maker"
- [ ] V²Site: Complete the section: "For DIY"
- [ ] V²Apps: V²Configurator: 1) Remove Wizards 2) Load Config xyz as Parameter in URL
- [ ] V²Panel: Arduino: Basic Firmware functions: Fan Control, RGB Lights, Remote Control
- [ ] Community: Marketing: Begin Projects to promote ViCase Pre-Orders, → #5 
- [ ] Community: At least 3 Pre Reviews out. Pre Reviewers can get Review Samples
- [ ] Community: Turn on Blogging on Progress, Decisions and new Articles. Open blog to Contribution Blogs.
- [ ] Community: Joint develop V²Community Shops / Referral Bonus Program #5 
- Clean up YouTube. Organize into Playlists. Create Video Title Images. (Finish what BC started)
# M05: Ship Pre-Order / Pre-Order Marketing
## Highlights
- **ViCase Community Pre-Order Marketing:** It is like a campaign. Only we are already in production. If we reach pre-order target we give away bonus, such as free Arduino.
- **Shipping Pre-Production Gamma Orders:** Further heating up ViCase Pre-Order Marketing Campaign 
- **Prepare Computex:** Pick a partner, Print Posters, Write Press Release, Package Samples
- **Google Adwords:** Develop Strategy, Design Adwords, Implementation
## Details
- [ ] Show: Prepare to exhibit V² → [Computex Taipai](https://www.computextaipei.com.tw/)
- [ ] Press Release: V² exhibit Open Source Mini & All-In-One PC at Computex Taipei
- [ ] Case: Cost Down Design (Tiny), 1 pcs CNC Cut Pre-Production
- [ ] Case: IQC Samples (Tiny), Assemble Case, Assemble ViPC-1, Compile ECR List
- [ ] Case: Finalize Design (Tiny), Generate CAM files, Put to Production, Qty as per Pre-Order Qty
- [ ] Case: Ship Qty (Tiny) as per Pre-Orders to customers
- [ ] Case: Cost Down Design (Mini), 1 pcs CNC Cut Pre-Production
- [ ] Case: IQC Samples (Mini), Assemble Case, Assemble ViPC-1, Compile ECR List
- [ ] Case: Finalize Design (Mini), Generate CAM files, Put to Production, Qty as per Pre-Order Qty
- [ ] Case: Ship Qty (Mini) as per Pre-Orders to customers
- [ ] PCB: Design in ECR. Production of Pre-Sales Qty, Beta Gamma
- [ ] Shops: Add Amazon, eBay, Newegg Shops with ViCase & V²PC Assembly Service
- [ ] Shops: Support Forum
- [ ] V²Site: Turn on Forum. Forum is used for joint support
- [ ] Community: Marketing: Push Projects to promote ViCase Pre-Orders, → #5 
- [ ] Community: At least 3 Reviews out (Review samples went to Pre Reviewers)
- [ ] Community: Get 5 more Pre Reviews, they will get in line for Pre Production Samples 
- [ ] Community: Spread Press Release / Promote V² at Computex Taipei
- [ ] Community: V²Panel: Arduino: Firmware Improvements: Fan Control, RGB Lights, Remote Control. Publish the Project in Fritzing and Arduino Playground
- [ ] Community: Google Adwords
# M06: Computex, ViPC & V²Community Shops
## Highlights
- **ViCase switch to regular sales:** Reduce Leat Time, remove discount offers in shops, end the pre-order campaign. If reached targets give away the stretch goal bonus items.
- **Computex Show:** Exhibit, Reach Press, Reach Housing Manufacturers, Reach System Manufacturers, Daily Video Reports
- **Launch ViPC:** Available in AmazonUS, Amazon DE, Newegg US, Newegg Taiwan, eBay Australia, eBay Singapore, Village Tronic Store for Asia
- **ViPC Community Marketing:** Same concept of setting targets with Bonus Give aways
- **Mass- Production:** ViCase Tiny and ViCase Mini is now in regular Mass Production
## Details
- [ ] Show: Exhibit V² → [Computex Taipai](https://www.computextaipei.com.tw/) Show ViCase & ViPC Trailblazer Products. Show all Standards completed and available for free download. Rapid Development Kits ready to ship.
- [ ] Case: Cost Down Design (Small), 1 pcs CNC Cut Pre-Production
- [ ] Case: IQC Samples (Small), Assemble Case, Assemble ViPC-1, Compile ECR List
- [ ] Case: Finalize Design (Small), Generate CAM files, Put to Production, Qty as per Pre-Order Qty
- [ ] Case: Ship Qty (Small) as per Pre-Orders to customers
- [ ] Case & PCB: First full production run as per shops order (Tiny and Mini)
- [ ] Shops: Add ViPC to Product Line
- [ ] two production runs / months as per shops order
- [ ] Community: 5 Reviews out (Review samples went to Pre Reviewers)
- [ ] Community: Launch V²Community Shops / Start Shipping ViPC
- [ ] Community: arrange for 3 Pre-Reviews of ViPC. Pre Reviewers can get Review Samples
# M07: Expand: Marketing & Sales & Production
## Highlights
- **Marketing:** Add YouTube Channel Marketing, Expand Google Adwords, Add V²Apps as marketing tools
- **Production:** All ViCase now in regular Mass Production. 
- **Sales:** Reduced lead time, availability of ViPC, availability in Major Store Platforms, Exhibition in Computex all lead to increased.
- **Support:** We are using the Forum for joint support. This month we add more posts to it to address common problems.
## Details
- [ ] Buy Lightworks
- [ ] YouTube: 4 Movies / month. Begin of YouTube Marketing. Put a Video list up and let community vote which one's are of most interest to be done first.
- [ ] YouTube Channel & Marketing: 4 Movies / Month — every month.
- [ ] Community: 3 ViPC Reviews. Pre Reviewers can get Review Samples
- [ ] Community: Promotion of V² YouTube Channel
- [ ] V²App Development: Add virtually exploring ViCase and ViPC to the stores
# Tasks
- [x] HC: Initial writing and release via Skype Conferences
- [x] HC: Collect feedback of GI via Skype Conference
- [x] HC: Rewrite after 1) Negative Cash Flow on Amazon 2) V²Site Home Page provided Structure
- [x] @georgillies Intensive feedback in Sunday's Skype Conference
- [x] HC: Include change request from ML → Comment below
- [ ] Rewrite into v4, as described on top and as per → #15 
- [ ] HC: Move to new Marketing Repository on V²

**Comment by VillageMichaelLin** [comment]
# Change Request
- M01: Start Samples of Pre-Production
- M02: Bring to life sample. Optimize design. Produce review samples
- M03: Final changes for Production, begin Pre-Production

**Comment by VillageHubertChen** [comment]
# Completely rewritten v3

Based on feedback from Sascha, Georg, Michael and Xiao Mao this is a completely rewritten and improved version. See the Revision History of v3 for more details. As always, let me know your feedback.

**Comment by bcaswelch** [comment]
Like the new layout. Looking to have reviews done by people such as linustechtips or other youtubers during the marketing phase could help a lot with publicity.

**Comment by VillageHubertChen** [comment]
Thanks for the compliment. We are getting very positive comments on the layout all across the board. We are now focusing on finishing the writing and then finishing the images. Then the Home Page will be completed.

Reviews from linustechtips, c't, Tom's hardware etc will be amazing. 

That being said, I suggest we first start to get reviews in smaller DIY PC forums and youtube channels. Lets listen to what they have to say and incorporate their feedback and see if we can get them to contribute. Once we can start building momentum with smaller sites we can move up ...
