### ISSUE TITLE
Road Map 2016 ... 2018 v1

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#11]
# Road Map 2016 ... 2018
### Q1: V²Site

_From now on progress to V² moves faster and is visible._
- **[Finalize Licensing](#FL):** Only the right Licensing Model will make V² successful
- **Contribution Management:** 
- **Contribution Workflow:** "
- **Example Project V²Panel:** 
- **Example Standard V²Panel:** 
- **V²Site Home Page:** 
- **GitHub Repository Structure:** 
### Q2: ViCase Trailblazer Products

_Reviews spread the word, selling products provides funding_
- **Product Pages on V²Site:** 
- **V²PC Community Project:** 
- **Launch ViSite with Shop:**
- **Donation:** 
- **ViCase Gamma Production:** 
- **ViCase Pre-Order Campaign:**
- **V²Case Press Campaign:** 
- **ViCase Review Campaign:** 
- **V²Configurator:**
### Q3: ViPC in V² Shops

_Availability in major stores improves access to users and funding to V² Organization_
- **ViCase Trailblazer Production:** 
- **Launch ViPC:** 
- **Amazon, Newegg, eBay:** 
- **YouTube Channel Marketing:** 
- **Weekly V² Video Tutorials:** 
### Q4: V² OEM Asia Campaign

_Begin the process to make V² Computer mainstream_
- **V²Site translated to Chinese:** 
- **V² Asia OEM Roadshow:** 
- **V² Guangzhou Open House:** 
### 2017.Q1
- ViDock and V²C Specs & Samples
### 2017.Q2
- ViDock and V²C standards
- ViCase Pre- Orders and Pre- Production
- Computex
- ViDock & V²C Video Tutorials / Channel Marketing
### 2017.Q3
- ViDock & V²C Mass Production
- Amazon, Newegg, eBay
### 2017.Q4
- Pushing Christmas Sales
### 2018.Q4
# The four major promotion stages in 2016
## Q1: V²Site

_From now on progress to V² moves faster and is visible._
This is the reference for all our work. It is also the fishnet to gain more contributors. We present an attractive common cause and we legally assure that work invested will always remain in Open Source and free of cost. We established true north plus efficient management of contribution so that work goes smoothly and in the right direction. 
## Q2: ViCase Trailblazer Products

_Reviews spread the word, selling products provides funding_
Nothing will tell the story better of what V² can do for the user, than:
1. A good "Pitch Video" 
2. Press News
3. Press Previews
4. Press Reviews

The Trailblazer products job is to show that the V² Standard is a real thing. The V² Site shows that the story and impact to the users is scheduled to be very big, as OEM support and mass production is already in the road map. 
## Q3: ViPC in V² Shops / Major press prepares OEM

_Availability in major stores improves access to users / Press coverage will warm up OEM_
In the last quarter we focused on DIY PC community and community reviews. With availability of ViPC in major stores and with the OEM Asia Campaign to be next it is the right time to approach the major press.
## Q4: V² OEM Asia Campaign

_Begin the process to make V² Computer mainstream_
We fully leverage our strengths to be located in the heart of computer production: Guangzhou, Donguan, Shenzhen, Hong Kong and Taipei are in front of our door step and make up 50% of computer production on this planet. We know requirements of local OEMs intimately. We will make it really easy for an OEM to start developing their new products to be V² compatible by: **1)** Translating the V² Site into Chinese **2)** Visiting the OEMs to demo V² with working products **3)** Blueprints are ready to be downloaded during the demo with easy acceptable licensing terms **4)** Working sample can be purchased during the demo so they can start engineering right away.
# Details on Road Map
### Finalize Licensing <a name="FL"></a>

The trick is to be comfortable for OEM yet beneficial and secure for V². We achieve this by three separate licenses for three separate intellectual properties of V²: 
1. **Standard:** CC-BY-SA-4.0 aka Creative Commons Attribution Share Alike. Only standard organizations would be interested in sharing standards. They can do it, but they would need to a) attribute us and b) need to do this under the same license. If they incorporate parts of our standard into their standard, their standard need to be shared under the same license too. This license is protecting that the V² Standard remains always open for all to use.
2. **Reference Designs:** CC-BY-4.0 aka Creative Commons Attribution. OEM would want to include parts of our reference designs without being forced to publish their designs. This is accomplished with this license. All they need to do is to attribute V².
3. **Logo License:** V²-Logo-License. This is a custom license. It will be very similar to Logo Licenses of other industry standards. We will allow use of the Logo free of cost under specific conditions spelled out. Particularly they need to pass the quality tests which the V² Logo represents to avoid confusing the customer and to avoid watering down the value of the V² Logo.
# Reference
- #10 Milestones
# Tasks
- [x] HC: Write Road Map, Initial Version
- [x] HC: Get feedback ML & LC → included
- [x] HC: Get feedback GI → included
- [ ] HC: Change big structure to follow: Community Campaign, Shops Campaign, OEM Campaign
- [ ] HC Add Press Campaign to Shop Campaign
- [x] @georgillies Completely analyze the Road Map

**Comment by bcaswelch** [comment]
Sounds promising, interested in hearing more about ViKik (but thats the far future, definitely keep it focused on the next few months (=  ).

**Comment by VillageHubertChen** [comment]
Thanks. Glad you agree on the road map. As for ViKik it is too early to talk about. Even to spell out ViDock is a lot of work. What I want to show is that from now on this is the pattern:
- **Q1:** Introduction
- **Q2:** Marketing
- **Q3:** Sales of Trailblazer
- **Q4:** Beginning of OEM shipping mass production

Every year we will repeat same pattern with new products.
