### ISSUE TITLE
Optimizing Spreading the Word and Products

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#15]
# Table of Contents
- [Proposed new structure](#new)
- [How it works](#how)
- [Old structure](#old)
- [Tasks](#tasks)
# Proposed new structure <a name="new"></a>
## Overview
- Social Web
- White Paper & Know How
- Blog
- Q2: Community Campaign
- Q3: Shops Campaign
- Q4: OEM Campaign
## Details

This is the new text for → http://v-squared.github.io/#spreading
### Social Web

We are on Facebook, YouTube, Twitter, Disqus and GitHub Issues. This is the easiest way to contact us, share V² with your friends or follow our progress. We are developing win-win scenarios with DIY Forums and Websites who share the same targets to improve the computer user experience.
### White Paper & Know How

A growing collection of White Paper and Know How Articles on the topics of developing, building, retailing, benchmarking, maintaining and repairing computer. Our aim is to become one of the best place on the web to find and publish computer know how on above topics.
### Blog

Latest News, Incubating Articles, Public Brainstorming. We share what we are working on in the early stages, giving you a heads up and a chance to give feedback or to contribute.
### Q2: Community Campaign

V²Case has been developed with the Community. This is our opportunity to give back with Community discounts on V²Case Trailblazer Products. And it is your last chance to give feedback on the product. We also need your continued support to promote V². Tell a friend or post a review. Help us to reach our stretch goal to earn free bonus products.
### Q3: Shops & Press Campaign

Ready build Mini and All-In-One PCs are becoming available in major stores, such as Amazon, Newegg and eBay. Or if you are (or want to be) a shop owner we have tutorials and case studies on how to add ViCase or ViPC to your existing store or even how to build one. With ViPC shipping and the OEM campaign coming it is a good time to approach the press.
### Q4: OEM Campaign

OEMs have the power to make the V² Mini and All-In-One PCs mainstream; to put them into the shop around your corner. We will demo V² with working products on our OEM tour in China, Hong Kong and Taiwan. We expect V² OEM products to become available in Summer 2017. We also have an "Open House" in Guangzhou for OEM developer to visit us and get answers to their questions.
# How it works  <a name="how"></a>

Additional writing on social media for V² → #16
### Social Web Home Page
- Facebook
- Twitter
- YouTube
- GitHub Issues
- DIY Forums & Site Projects
### Facebook

This is the ViDock Community where the whole V² Project was born. We have neglected since December. We need to show face again. Also we need to show a future for ViDock. Probably best to have minimum product pages finished before making an appearance :-) This can be done soon by using the Trailblazer Pages on V² Site and by utilizing images and text that we already have prepared. We are also adding the Twitter to our social media. With it we will split content like so: Facebook: Consumer & Products, Twitter: Technology and Standards. Once in a while we will promote a highlight article of the other side, to let new readers know that the other social media site exists
### Twitter

We have a Twitter account for Village Tronic but we never really used it. Twitter is gaining popularity and it is more acceptable to developers than Facebook. As such we will create a V-Squared Twitter Page and focus on it on developer / V² topics.
### YouTube

We have the YouTube channel VillageViDock since a long time and we will add the content of V² to it. We need to finish the task the Bobby started to add Cover Images to the Videos and sorting the Videos into Playlists. As such we will add the V² Playlist and put it on top. The first Video that we will be making is the V² Pitch Video. This might be for a long time the only Video from us. But once we start shipping V² Case Gamma there might be lots of third party reviews or comments coming up that we can publish there. Eventually we will reach a point where we will produce one movie per week when we start our YouTube Channel Marketing. This is expected in Q4.
### GitHub Issues

GitHub issues is ideal to check out what we are working on or to report bugs or improvement ideas. We are very active and responsive on GitHub Issues, as it is also used to manage our work. As such you can consider GitHub Issues the best Social Media to get in touch with developers of V².
### Disqus

Disqus is becoming the leading social media site for discussions and feedback. E.g. the Lightworks community as changed to disqus. Our blog is made with Jekyll and it has a disqus plugin. This way we can show use replies directly under the blog posts. It is to be expected that a lot of know how will be posted by the users too. By posting it in disqus it is searchable on a broader scale, by a wider community, and as such should bring more traffic to the V² Blog and make its content more accessible.
### DIY Forums & Site Projects

Like it said on the label, we will be looking for Win-Win projects with other forums and sites. An example is that we will put upgrade and repair instructions of ViCase on iFixit. We will also put into our standard that it is required for any V² Use licensee to have the respective product's repair instructions on iFixit. We hope this will earn us some honorary mentions on the iFixit Web site. We may be the first standard organization making using iFixit mandatory. Good for iFixit, good for the user and good for the manufacturer, as his customer can enjoy a better product service and thus will be more loyal to the brand. Other projects ideas include:
- Work with Lightworks community to develop ViPC-Lightworks configurations
- Work with Solidworks community to develop ViPC-Solidworks configurations
- Work with Photography communities to develop ViPC-Photography configurations
- Work with Tony Mac X communities to develop ViPC for X configurations
- Work with Photography communities to develop ViPC for MacOS configurations
- Work with Steam communities to develop ViPC for Steam (with Win 10) configurations
### Home Page: White Paper & Know How
- **Invitation to Open White Paper & Know How Video** A recorded Skype Video Interview between Bobby and me on why to make the Blog. Topic are our passion of sharing know how, invitation to provide feedback and improvements and invitation for guest authors (We will record Video and Audio Local and will edit in LightWorks)
- **Paper & Article List** Same layout and structure as V² Home Page.
### Home Page: Blog
- **Invitation to Blog & Dialog Video** A recorded Skype Video Interview between Bobby and me on why to make the Blog. (We will record Video and Audio Local and will edit in LightWorks)
- **Highlight Articles** List of special Articles Folio Graphics. Linked to the actual blog entry
- **The Blog** The real thing
### Why V² Blog

In any given week I (HC) write at least ten Articles. In the context of the V² Community many are of public interest and on many I wish to get feedback. The Blog is (for me) the long awaited platform to put these Articles to good use. To grow the community by building a readership for these blog Articles. To get more feedback to ensure we are moving in the direction the community actually wants. Blog posts will be promoted on our Social Media Pages. The blog would also be the place to announce and comment major updates to the V²Site.
### What is a campaign

The dictionary defines a campaign: "A series of related operations advancing toward a particular goal". This is exactly what we 
### A campaign is focusing all activities of a quarter

I already have written 3 previous versions of Milestones → #10 . Each time attempting to bring all projects into a focus. Without success. The approach of one campaign per quarter allows me to really bring all projects of a quarter into focus. To have an easy understandable target for each quarter which all projects are geared towards.
### Each quarter has a different campaign

Three months is a long enough to achieve a substantial goal and not too long to run out of steam. By starting a new campaign each quarter we can conclude and celebrate each campaign each quarter. And we can make a quarterly review process on how we did on the last campaign to see if there is something to learn to make the next campaign even better.
### Each campaign is growing in reach

The campaigns are developed as a sequence, where each campaign rests on the shoulders of the previous campaign. And the sequence is geared towards reaching V² True North: Making V² Mainstream. Lets look at the next 3 campaigns from this perspective:
- **Q2: Community Campaign:** Reach ~ 5k members of our community and some more with guest posts in other communities
- **Q3: Shops & Press Campaign:** Reach: 100K ... 1M impressions on accumulated online shop pages impressions, press news, reviews. 
- **Q4: OEM Campaign:** The ultimate reach > 10M. Once OEM start shipping they should reach millions with accumulated impressions of advertisements, product page visits, reviews of various products of various OEMs in various press. However, this will only be reached after OEMs are shipping, which should be middle of 2017. This campaign is but the beginning of the OEM program.
### The Community Campaign
- **Gamma Samples:** _ViCase Mini Gamma_ 10 pcs (used in community reviews)
- **Sales Goal:** _ViCase Mini Trailblazer_ 100 pcs
- **Stretch Goal 1:** _ViCase Mini Trailblazer_ 200 pcs → Free Arduino
- **Stretch Goal 2:** _ViCase Mini Trailblazer_ 400 pcs → Free ViCase Cooler L
- **Campaign End:** June 30th
- **Shipping:** July 30th
- Supporting Pages / Sites / Apps
  - Village Tronic Site & ViCase Product Pages
  - V²Configurator
  - ViPC Configuration Pages
  - Assembly / Upgrading / Repair Pages on iFixit
  - Time lapse assembly Video 
  - White Paper and Know How Articles
### Supporting Projects
- Complete the Campaign Video
- ViCase Mini Gamma Sample Production
- Complete Village Tronic Site with Product Pages and Online Shop
- Determine Product weight, volume, shipping costs
- V²Configurator
- ViPC Configurations
- ViPC Reviews specialized on use case, such as video editing
- Google Adwords
- Assembly / Upgrading / Repair Pages on iFixit
- Time lapse assembly Video 
### The Shops & Press Campaign
- **Gamma Samples:** _ViCase Tiny & Small Gamma_ each 10 pcs (used in community reviews)
- **Sales Goal:** _all three ViCase Trailblazer Models_ 300 pcs
- **Campaign End:** Sep 30th
- **Shipping:** Mini should be in stock, Tiny and Small to be in stock end of August
- Supporting Pages / Sites / Apps → Same as in previous campaign. Added models Tiny & Small
### Supporting Projects
- ViCase Mini Trailblazer Production
- ViCase Tiny & Small Gamma Production
- ViCase Tiny & Small Trailblazer Production
- Opening Amazon Stores in US, DE, UK
- Opening Newegg Stores in US, Taiwan
- Opening eBay stores in US, Singapore, Australia
- Adding ViPC to Village Tronic store for Asia markets only
- Press Releases: 
  - ViCase: First case build to follow V² Open Modular PC Standard is shipping 
  - ViPC: First PC build to follow V² Open Modular PC Standard is shipping 
  - First PC on iFixit before shipping
  - V² OEM Roadshow is open for registrations
### Home Page: First OEM Campaign
- **V² OEM tour:** 
  - **Tour Duration:** October
  - We visits OEM that registered with the tour in China, Hong Kong and Taiwan. 
  - On site we demo: ViCase Tiny, ViCase Mini, ViCase Small, ViPC 1, ViPC 750, ViPC 970. 
  - We explain Licensing Model. 
  - We show benefits of V² OEM Kits. 
  - We demo how to find all you are looking for on V² Site. 
  - We show workflow of: Big Reporting, Contribution of a Fix
- **V² Open House:** In Nov, Dec we have Open House. That is any OEM V² Developer can visit us without the need of making an appointment. We will offer Kung Fu tea, a view into our development and production and will answer any of their questions.
- We will repeat the OEM Campaign in Q1 and Q2
- We are exhibiting at Computex 2017 and will visit Taiwan OEM subsequently to the show

We expect V² OEM products to become available in Summer 2017. We also have an "Open House" in Guangzhou for OEM developer to visit us and get answers to their questions.
# Old structure as per March 31st   <a name="old"></a>
- Kept for Reference*
## Social Media

The easiest way to contact us, find out what others are saying about V² Modular PC or to let your friends know about it. We are on Facebook, Twitter, YouTube and GitHub Issues.
## DIY Forums & DIY Websites

V², DIY Forums and DIY websites all share the same goal of making building, upgrading or repairing a custom PC easier. Here we are looking for Win-Win scenarios to help and promote each other
## Press

V² modular PC saves the environment and the user's money. It breathes new life into the Desktop and delivers faster, quieter and more portable PCs. Help to spread the word. Find Press Releases, White Papers and more ...
## Stage 1: V² Trailblazer Products

V² Gamma Sample Products ship in June, Trailblazer Products ship in August. Enjoy the benefits of V² Modular PC before they become available through OEM offerings, or be one of the first to write about it. The first 100 orders will enjoy a 25% discount. Help to spread the word to reach our 200 pcs stretch goal to get a free Arduino.
## Stage 2: V² Shops

1) Listing of all shops selling V² Products. 2) Tutorials on how you can build your own V² Community online shop. (e.g., Computer Clubs and DIY forums to offer a service to their members that saves their money and at the same time generates income.) 3) How you can add custom build Mini and All-In-One Workstations to your existing shop.
## Stage 3: V² Consumer Products

OEMs have the power to make the V² Mini and All-In-One PCs mainstream, to put them into the shop around your corner. We are demoing V² on our OEM tour in Q3 in China, Hong Kong and Taiwan. We expect V² OEM products to become available in 2017.
# Tasks  <a name="tasks"></a>
- [x] Write new Structure, get initial feedback from VC, SL
- [x] HC Add Press Campaign to Shop Campaign
- [x] Get final feedback from SL after final writing → Sounds almost too good to be true :-)
- [x] HC: Write about how it works
- [x] @georgillies Give feedback in comment
- [x] @bcaswelch  Give feedback in comment.
- [x] Move new Portfolio writing to V² Home Page
# Reference
- → #10

**Comment by VillageHubertChen** [comment]
@bcaswelch Give feedback in comment.

**Comment by georgillies** [comment]
I think this ímproves the existing text. "Q" instead of "Stage" may be contraproductive in case of unforeseen changes.

**Comment by bcaswelch** [comment]
Sounds good! Lets talk more about the personal shop but I think this is all moving in the right direction. The marketing should give plenty of opportunity to get word out.

**Comment by VillageHubertChen** [comment]
Transferred new writing on "Spreading" to V² Home Page JSON. Last task to to close this issue. The really last task will be to convert it into an Article on "Marketing" :tada:
