### ISSUE TITLE
Newegg Combo Deals

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#3]
# Example / Hero

![newegg-combo](https://cloud.githubusercontent.com/assets/7278716/13625906/848a30d8-e5f7-11e5-8691-d27c21334981.png)
- [Newegg►Combo Deal](http://www.newegg.com/Product/ComboBundleDetails.aspx?ItemList=Combo.2592316)
# A single click shopping list

A complete PC. All parts are nicely listed. One can buy all the parts with just one click. It is convenient to explore its features, its parts and the details of the parts. It is also convenient to see where you spend your money (heavy on CPU, heavy on Disks, etc ...).
# Alternative to sell complete PCs

This could solve our problem in #1 like so
1. We already have a lists for a Newegg Combo Deals. All we need to do is to set up the Combo Deal in Newegg
2. We can make two options for Combo Deals: 
   1. Without Assembly Service. So buyer need to build himself.
   2. With Assembly Service. An additional $100 line item. PC arrives build and tested at buyer.
3. Buyer can buy a complete ViPC with a single mouse click
4. The V²Community Shop Owner does not have the negative cash flow issue as in #1 
# Benefits for V² Community Shop Owner
- Taxation becomes very simple, as no high revenue go through V² Community Shop Owner's bank accounts
- All Legal matters are clear: V²Communnity Shop only renders assembly service. The Shop is not a PC manufacturer from legal point / commercial of view.
- No cash risk. This allows to keep assembly fee low
- New Story to tell: "Best of both Worlds". Gives additional opportunities for marketing.
# Difference of V²PC and ViPC Combo Deal
## V²PC Combo Deal (DIY)

Newegg customer buys the Combo Deal and enters his shipping address. Parts arrive, he assembles it to a working PC.
## ViPC Combo Deal (Finished Custom PC)

Newegg customer buys the Combo Deal and enters the V² Community Shop's shipping address. Parts arrive at the shop. The shop assembles them into a working PC and test it. The customer receives a working PC.
# Reference
- #1 
- #2 
# Bonus
## Newegg in Asia!
- http://www.newegg.com.tw/ Taiwan
- http://www.newegg.cn/ China
# Tasks
- [x] @bcaswelch Introduce the idea of Newegg Combos to HC
- [x] @villagehubertchen Agree that we want to try this way. Create an issue on this topic, assign BC
- [ ] @bcaswelch Research Newegg Combo Deals: 1) What are the requirements for you to create a Combo Deal? 2) What are the hurdles for you to overcome? Write report into comment of this issue.
- [ ] Nino: Read this card. Discuss with HC on today's conference call. Is there a similar online shop in Germany that offers something like Newegg Combo Deals?

**Comment by bcaswelch** [comment]
Would you include a copy of windows in the DIY combo? Most neweggs combos come without a copy of windows. Might not be a bad idea to leave it out because a lot of people may already have a hard drive with windows or are more than capable of buying it themselves.

**Comment by VillageHubertChen** [comment]
Agreed. This is very easy to add, but not easy to take out! Good point!
