### ISSUE TITLE
ViPC Commerce Options

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#4]
# Introduction
## All Options address Negative Cash Flow Issue

The negative cash flow issue was discovered by Nino and is described in detail in Issue #1.
## Benefits to User Stories describing sales options

We are striving to deliver a great shopping experience to the ViPC buyer. User Stories are a tool in 
_Rapid Development_, that is especially suitable for our purpose. They are fictional stories written in the personal view point of the user who is experiencing the finished product. So while designing the shopping experience we already do this from the point of view of the buyer.
# Listing of ViPC shopping options
1. [Traditional DIY](#trad-diy)
2. [V²PC DIY](#v2pc-diy)
3. [Newegg Combo V²PC DIY](#newegg-v2pc)
4. [Newegg Combo ViPC](#newegg-vipc)
5. [ViPC in Major Store Platform Initial](#major-store-initial)
6. [ViPC in Custom Store Platform](#custom-store)
7. [ViPC in Dual Store Platform](#dual-store)
8. [ViCase + Assembly Service](#assembly-service)
9. [Standard ViPC vs Custom ViPC](#standard-vs-custom)
10. [ViPC in Major Store Platform Expanded](#major-store-expanded)
11. [Selling ViPC in Asia](#vipc-in-asia)

Below we will look at the different options in more details:
# Traditional DIY <a name="trad-diy"></a>
## User Story

As an **experienced DIY PC** assembler I know exactly what parts I want and how to assemble the PC. I looked up the features of ViCase and found it delivered what I need. I will find and buy all parts that I need to assemble my PC, then assemble it. I appreciate that ViPC is available in different Store Platforms, so I can choose the one I am comfortable with.
# V²PC DIY <a name="v2pc-diy"></a>
## User Story

As **experienced DIY PC assembler looking for a shortcut** or **not experienced DIY PC** assembler I was looking for a ready made configuration that match exactly the PC that I wanted to build. This would save me the time to create a configuration myself and to double check that all parts are compatible with each other. V²PC delivered on this account. They have over 15 models, described with features and comparison tables to choose between them. This enabled me to quickly find one model that was very close to what I wanted. Next I could load the model of my choice with a single click into the V²Configurator and  customize it to exactly the configuration I wanted. Ordering was easy. I picked the online store of my preference and checked out all the parts in the list. The rest is business as usual. The parts arrived and I assembled my PC.
# Newegg Combo V²PC DIY <a name="newegg-v2pc"></a>
## User Story

As a **Newegg Veteran** I am familiar with their _Newegg Combo Deals_. It is a convenient way to explore a custom PC assembly list, made all of Newegg parts and presented in the Newegg Universe with lots of cross links within this universe. This enabled me to explore and undertstand the PC configuration I was interested in. Also check out is more convenient with a Combo Deal, as it is only one check out for all parts, rather than checking out each part by itself.
## Issues
- → #3 (Newegg Combo Deals)
# Newegg Combo ViPC <a name="newegg-vipc"></a>
## User Story

As a **Newegg Veteran** I am familiar with their _Newegg Combo Deals_. If you are not, read the User Story above. The interesting difference of the ViPC Version is that I do not need to assemble the DIY PC myself. The Combo Deal includes the _Assembly Fee_ With it I pay the V²Communnity Store to assemble and test the PC for me. So I receive a fully working custom PC.
## Issues
- → #3 (Newegg Combo Deals)
# ViPC in Major Store Platform Initial<a name="major-store-initial"></a>
## User Story <a name="story-major-store-i"></a>

As a **frequent buyer** in **Amazon** or **Newegg** or **eBay** or **Taobao** I appreciate a lot that ViPC is listed in my favorite Store Platform. Frankly speaking, if it were not listed, I would not even have found it, as I rarely search in other places when I am looking to buy something. BUt being listed here 
## Issues
- → #1
# ViPC in Custom Store Platform<a name="custom-store"></a>
## User Story <a name="story-custom-store"></a>

As a **buyer of bleeding edge electronics** I am used to search hard to find what I was looking for. Thanks to your Google Adwords or thanks to some friendly posts with your shop'd URL I found ViPC in your custom shop. I was of course concerned to spend $1000 on a small shop I never bought from. But you got good reviews and everything seemed to be proper maintained and our email conversation was nice. So I took the plunge and bought with you. You did not disappoint me. Thanks.
## Special Procedure for Shop Owner

In our initial use of Major Store Platforms the Shop Owner might limit the available quantity to one piece. This way the shop owner limits the effects of the negative cash flow as described in → #1 to finance one PC for the duration of a few days. Once he shipped the ViPC the the Shop Platform will release the funds, which however could still take a few days to show up on his Bank.
## Issues
- → #7
- → #8
# ViPC in Dual Store Platform <a name="dual-store"></a>
## Summary

This approach gives us the best of both worlds and then some. 
### Found in Major Store and bought there

<a href="story-major-store-i">User Story bought ViPC in Major Store</a>
### Found in Custom Store and bought there

<a href="story-major-store-i">User Story bought ViPC in Custom Store</a>
### Found in Major Store, bought in Custom Store

As an **experienced shopper looking for best deals** I was browsing the **Amazon** store and found ViPC. Then I searched "ViPC Store" in Google and found your Store. Your offering is lower cost than in Amazon, so I bought it in your store.
### Found in Custom Store, bought in Major Store

As a **careful shopper** I was browsing the internet in search for a custom build PC with fair pricing. I found your store through Google Ad Words and through kind users who posted a URL to your store in DIY PC forums. I liked your store and ViPC, but I was worried to spend this much money with a small store. I was very grateful when I found the link to ViPC in Amazon, eBay and Newegg. I picked the store I usually shop in. I noticed that it is more expensive in the major store, but I still bought it there, as the additional protection through the major store was worth to me the extra cost.
## Issues
- → #1
- → #7
- → #8
# Assembly Service <a name="assembly-service"></a>
## User Story

As a **DIY Custom PC Builder** I was browsing the case section of my favorite major online stores: **Amazon**, **Newegg**, and **eBay** and I came across ViCase. I already liked it very much. When exploring the store offering ViCase I found the _Assembly Service_ Item. I was very intrigued. I only assembly custom PC as buying a ready assembled custom PC is so expensive. The ViCase Assembly Fee instead is more reasonable. I also liked that I was offered different options, such as <a href="v2pc-diy">V²PC DIY</a> or <a href="newegg-v2pc">Newegg Combo ViPC</a>. Although I started with the plan to build the PC myself, I ended up using the Assembly Service. Thanks for offering an option that is almost as low cost as a DIY build Custom PC and almost as convenient as buying a ready built custom PC.
# Standard ViPC vs Custom ViPC <a name="standard-vs-custom"></a>
## User Story

As a **careful buyer using only major store platforms** I was first put off that the Custom ViPC were not possible to return against money. But when I found out that I could return your Standard ViPC Models and that the Custom ViPC would be purchased and assembled only for me, following my exact specifications I could understand your point of view. Now I think it is fair that I can choose from a Standard ViPC that I can return or a Custom ViPC that I can not return.
### Standard ViPC
- Very few standard models
- The models we have are the ones most in demand
- No customization
- Customer can return Standard ViPC versus money back
### Custom ViPC
- Lots of custom models
- Models are more specialized
- On top of many models the customers can customize the config with V²Configurator
- Customer can NOT return the Custom ViPC
# ViPC in Major Store Platform Expanded <a name="major-store-expanded"></a>
## User Story

As a **frequent buyer** in Amazon it was really easy to find your ViPC offerings. I searched for most reviews or best rated reviews and in both I found your ViPC listed on the first page.
## Details for Shop Owner

In the initial offerings the Shop Owner limited availability of Standard ViPC Models to 1 piece. This limited his risk of financing the negative Cash Flow → #1 that comes with selling in Macor Store Platforms. In time sales quantity went up and so did confidence. Since financing the few days between buying parts and funds released became the bottle neck in earning money but at the same time confidence and experience was present a way was found to finance larger quantities. Sales when up accordingly.
# Selling ViPC in Asia <a name="vipc-in-asia"></a>
## Details for Shop Owner

Selling in Asia is similar to selling in the USA. We will not repeat here all what we have said above. Please read all of the above. However a few things are different in Asia:
1. **Major Store availability:** Amazon is not available, but Newegg, eBay and Taobao are
2. **Convers to be copied:** see the referenced issue
3. **Almost all shipping is international:**  see the referenced issue
4. **We are local:** This makes things easier for us
## Issues
- → #9
# Reference
- [Competition: ViPC Workstation](https://github.com/V-Squared/v2-How-to-DIY-Mini-PC/wiki/Competition:-ViPC-Workstation)
# Tasks
- [x] HC: List all Options and document them
- [x] GI: Give feedback. Best in skype conference with HC → Comment
- [x] HC: Rewrite after feedback from GI
- [ ] XiaoMao: GIve feedback to HC
- [ ] @bcaswelch : Give feedback. Best in skype conference with HC
- [ ] HC: Write Conclusion. Close issue.

**Comment by VillageHubertChen** [comment]
# Feedback from Georg
1. DIY-Option: Kunde kauft Einzelteile, baut selbst (ist wie bei Indigogo)
2. Kunde kauft Bauteile und schickt sie an Shop ("Assembly service", dass ist innovativ)
3. Newegg Combo (geht das?)
   a) ohne Assembly
   b) mit Assembly
4. Bankkredit  ← Diese Lösung fehlt #4
5. Onlineshop-Lösung (s.o.)
6. In Amazon: Setze Limit auf 1 Stück!  ← Add to the corresponding #4

Zu 2.: Vorgesehen Werbung über Amazon, dort wird ViCase angeboten (gute Idee!)

# Tasks
- [ ] @villagehubertchen Add missing points as per above post

**Comment by bcaswelch** [comment]
Like the user stories, the reasoning all make sense. 

Once the website/shop is more finalized I might show it to some friends and see what their overall impressions are; I have friends that do quite a lot of their own computer shopping but also some that just get whatever they see at best buy. Never hurts to have more viewpoints.

**Comment by VillageHubertChen** [comment]
I am glad the User Stories make sense. So we will use these to guide us in our future decisions. This will safe a lot of time in documentation and should help us to stay spot on to deliver what the user wants.

More feedback is also great, of course.

In order to get it as fast as possible I suggest:
1. We work together to get the basic contribution function of V² site working
2. You work with Configuration Communities to finish V²PC configuration
3. Each time one V²PC configuration is finished, Lukas and me will design a shop page. 
4. For each shop page you can start getting feedback and use it to make the next V²PC configuration even better :-)

I agree to get as much feedback and as frequent as possible!
