### ISSUE TITLE
ViCase Referral Bonus Program

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#5]
# Basic Idea

Finding customers is an effort. As V²Commnity we share this effort. Finding a customer has the reward of generating revenue. As V²Community we share this too. With the ViCase Referral Bonus Program.
# How it works

Just like other referral bonus programs, such as from Amazon, B&H, Newegg and cohorts. A community member applies for it. We provide a key to the URL. Anybody who buys with this key will generate bonus for the community member. The bonus can be paid out either in cash or in shipping ViCase products.
# User Stories
## ViPC Community Shop owner

As a ViPC Community Shop owner I have two options to benefit from my marketing activities:
1. **I sell ViCase myself:** I stock ViCase in my shop. All my marketing activities point to my shop. When I sell ViCase I earn the money. I also have the efforts of financing stock, shipping and technical support.
2. **Referral Sales:** Village Tronic stocks ViCase, handles technical support and ships to customers. They have local warehouses in Europe and UK. It is same convenience to the buyer. I have no any work with it.
## Student building DIY PC

As a student I am on a very tight budget and I need a PC with special requirement. Custom building a PC provided lowest cost and gave me the chance to build exactly the PC I want. When researching the Housing options I learned about different case options. I found ViCase and like it very much. Especially the portability combined with high performance, so it is easy to bring my PC home or to friends. I fell in love with the V²Community and their Open Source concept and easy collaboration. I love to spread the word about it so more people know about it. They even reward me to do that. I applied for the Referral Bonus Program and got a special URL, that I am using in posts in other forums. If they eventually buy a ViCase, I get a bonus. This way I got a ViCase for free! 
# Tasks
- [x] HC: Write initial Article
- [ ] @bcaswelch Give feedback
- [ ] Nino: Give feedback
- [ ] @georgillies

**Comment by bcaswelch** [comment]
Like it! Provides incentive for people to talk to friends/family about it. Wouldn't mind taking this a step further with getting community members involved with activities such as possible givaways or other opportunities. But this would be much farther down.

**Comment by VillageHubertChen** [comment]
Actually I want to pull this in as much as possible. If we use the approach with referral links we would need to wait to have a custom shop. If you have ideas on how we can give referral bonus once we start selling with a traditional shop, that would be very exciting. The more incentive we can give, the more the community shall get involved. And I find it more than fair. If we go through a major store we need to share profit with them for promotion of ViCase. I rather share it with our community :-)
