### ISSUE TITLE
ViCase Pre-Orders / Community Marketing

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#6]
# Pre-Order Discounts
- **30%** for first 10 ViCase
- **20%** for first 11 ... 100 ViCase
- **10%** for first 101 ... 200 ViCase
# Community Marketing Bonus
- **Free Arduino:** > 200 sold ViCase
- **Free RGB Lights:** > 400 sold ViCase
- **Free Cooler-L:** > 800 sold ViCase
# Products
## Discounted ViCase
- 3 x ViCase Sizes: Tiny, Mini, Small
- Lower price than final production price
- Ships about 2 month after campaign ends
## Beta ViCase
- 3 x ViCase Sizes: Tiny, Mini, Small
- 3 x schedules, in order of shipping: Tiny, Mini, Small
- Higher higher price than final production price
- Shipping starts during campaign
## Group Packages with discounts
# Story: Simply the best Mini PC DIY Case
- Elegant, Small, Quiet, High Quality, Aluminum
- Easy to assemble: Access from all sides
- Only standard desktop parts: High performance, cost efficient, easy upgrading
- Most Accessories: Feet, Access, Bracket, RGB Lights, Cooler, Stand, Remote
# Side Story: Easy DIY with V² Open Source
- Ready configurations with complete shopping lists → V²PC
- Easy customization of your Config → V²Configurator
# Side Story: World's first Mini / AiO Standard
- All V²Standards are finished and published under CC & MIT License
- All Blueprints are available in Open Source under CC & MIT License
- All Designs in FOSS: Arduino, Fritzing, KiCAD, FreeCAD
- Rapid Development Kits very low cost, physical part shared with ViCase products
# Stretch Goals
- Free Arduino
- Free RGB Lights
- Free Cooler XL
# Platform
## Exploring three Options
1. Our own Site
2. Indiegogo
3. Kickstarter
# Schedule
## Order
1. V²Site: On GitHub. Focal point of community activities and contributions
2. V²PC: Ready to build configs with shopping lists
   - Community Development on V² GitHub
3. V²Configurator: Easy to explore configurations
   - No Wizard, just select a Config to get started
   - V²Configs links to load Configs (deep links)
   - Checkout supports: Amazon US, Amazon DE, Newegg US
   - Community Development on V² GitHub
4. V²Site: Standards
   - Publish all Standards, MIT & CC License
   - All Designs in FOSS: Arduino, Fritzing, KiCAD, FreeCAD
   - Community Scrutiny on V² GitHub
5. ViSite: Cool looking product pages
   - Community Development on V² GitHub
6. ViShop Pages: Demo Product in Shop Context, make comparable to other products / shops
   - Build with Jekyll + UI Kit. actual shopping not needed at this time
   - Community Development on V² GitHub
7. Build Campaign on V² GitHub with community feedback in Text and Images
   - Only tease features on high level
     - who wants to know more, linked to V²Site, Configurator, ViSite and ViShop
   - Community Development on V² GitHub
8. Pitch Movie: 1) Show real sample in use 2) Why we build it 3) Engineering Skills
   - Community Development on V² GitHub / Movie clips on Flickr
9. Check with Indiegogo / Kickstarter if they want to promote it
   1. If they make commitment to promote it, we launch on their platform
   2. If they do not make a commitment to launch, we make it on our site
10. Launch
11. Campaign Marketing
    - Mailing our ViDock Customers
    - Facebook Community
    - Community Members post about it in DIY PC forums
    - published lined up reviews in YouTube review channels
## Launch Date and Duration
- **Launch:** May 16th
- **Duration:** 30 days
# Tasks
- [x] @villagehubertchen Writing Initial Article
- [x] @villagehubertchen Add Campaign to V² Home Page → V-Squared/V-Squared.github.io#1
- [x] @villagehubertchen Collect review from Sascha in daily conference call → Comment
- [ ] @villagehubertchen Adjust Milestones to reflect ViCase Campaign 
- [x] @georgillies Intensive review / feedback to HC → Comment
- [x] @bcaswelch  Initial review / feedback to HC → Comment
- [x] @bcaswelch  Intensive review / feedback to HC → Comment
- [ ] Nino:  Intensive review / feedback to HC

**Comment by VillageHubertChen** [comment]
# Feedback Sascha

Change Campaign to not have a campaign target. This will put people into a standby and wait position to see if will be successful. Instead say the first 10 buyers get 30% discount, next 100 buyers get 15% discount. This gives an incentive to buy earlier than later. After than the stretch goals give further incentive, even if the supporter already did buy. If he helps to get more buyers, he can get the stretch goal bonus'.

**Comment by VillageHubertChen** [comment]
# Feedback Georg

## Don't call it campaign!
- Reminds of failed Indiegogo Campaign
- Makes people think product still need to be developed

## Call it Pre-Sales
- Correctly implies that product is already in pre-production
- Suggests discounts and urgency to catch limited availability

## Community Marketing Bonus instead of  Stretchgoals

Same reasoning. Stretchgoals remind of Campaign. Campaign suggests that the ViCase development is not completed yet, whereas it is. 

# Changes applied

I made changes in first comment of this Issue.

**Comment by VillageHubertChen** [comment]
# Feedback Bobby
- He had no negative connotation with campaign, but can see how it appeared bad to Georg and Sascha
- He likes "Community Marketing Bonus"
- Overall concept looks good. More tomorrow.

**Comment by bcaswelch** [comment]
I think some pre-marketing/publicity needs to be done with the pre-sale campaign if done with kickstarter/indiegogo again. A lot of campaigns will go out and generate buzz prior to releasing to have a big push. Not sure exactly how to do this, but definitely should focus some attention to pre-marketing.

**Comment by VillageHubertChen** [comment]
Two topics. I a m replying one by one:

## Pre-marketing

I agree wholeheartedly on the need of pre-marketing! And the plan is to start as soon as possible. To get the community really involved. I want we are looking for projects where you can add to the needed content on V² and at the same time get relevant communities involved to give at least feedback, better even to contribute content as well, ideally content they already have or at least on topics they are already experts. 

The best I found so far would be to finish all V²PC configurations and in doing so work with Configuration Forums.

If we can get these communities involved we get:
1. Feedback: Are we on the right track? Do we provide value to these communities?
2. Contribution: They can help us to create needed content
3. Recognition: The people involved and there friends will learn about V²
4. Promoters: If they really love what we are doing and see the value, they will promote it

Once we get promoters we are ready to push the pre-sales campaign

## Kickstarter / Indiegogo Campaign

This is my current feeling on putting the campaign up on Kickstarter / Indiegogo: We will first make our own campaign and get promotion / pre-marketing out and see if we can get any grip with it. If not, we change until it causes traction. Once it does, we will try to contact both Kickstarter and Indiegogo and see if they agree to promote it. If they do, they project should receive a push by them. But if they do not, I am not sure just by being on Indiegogo or Kickstarter will make the project more known. Right now it feels the project is as much known as in the following formula:

Project popularity = Project attractiveness \* our marketing effort

As such Indiegogo and Kickstarter are not helping. They are only the web hosting service and layout template and shop. Since we already have hosting service and shop and we have a better template, they only add cost and reduce layout power. 

But this is only my current thoughts. You are welcome to comment. However, I first really want to come to the point that we have finished the campaign on our pages, have the product in stock and our pre marketing efforts are showing results. After that would be a great time to discuss Indiegogo and Kickstarter :-)
