### ISSUE TITLE
Developing Custom Store Platform

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#7]
# Executive summary
1. Pick a redy build eCommerce that is trouble free
2. Pick trouble free Hoster, expect $1 / month. 
3. We build Village Tronic's shop first and make it bug free and easy to maintain
4. We build a V² Community Demo Shop with future shop owner (Nino, Bobby, ...)
5. Shop Owner installs shop on his hoster, completes customization
6. Shop Owner starts sales on his own shop
#1) Criteria to Pick eCommerce solution
## Easy support for major payment systems

We want customers can pay at least with PayPal and Major Credit Cards. The more the merrier. And we want that setting this up is easy.
## Data and transaction safety

The solution must be safe
## Pick SW Stack can be hosted anywhere

That would be HTML + MySQL + PHP. 
## Pick clean API between Front to Back

We want to give the front end our own look and feel. We shall pick an eCommerce solution that allows customizing the look and feel with little effort and little time spend in debugging.
## Pick easy shop customization

The shop owner is not expected to code. We need to pick an eCommerce solution that is either easy to be customized in the backend only, or we can add the missing customization easily by moving them into JSON files.
## Do not use Joomla or Wordpress

Our experience is that they require more upkeep and they limit choices in eCommerce solutions.
#2) Picking a hoster

The eCommerce solution will not have much demands on the hoster. A $12 / Year plan of any othe major hoster will do. Nino and Bobby should pick one that they like.
#3) Build Village Tronic's new shop

We want to walk away from Joomla. So we need a new shop anyways. We will pick our shop solution to be sutable for V² Communnity Shop Owner as well. All testing and customization is done considering that once the Village Tronic shop works, we will use it as a template to build the V² Community Demo Shop
#4) Building the V² Community Demo Shop
## Run on suggested hoster

We build a prototype shop on the suggested hoster. We populate it with $1 parts, so we can do real shopping on it to test all its functions. Community review is also possible. 
### Use customization of eCommerce solution

Wherever the shop allows for customization in the backend, we will use it.
### JSON where possible

When we customize HTML and CSS of the front end, we will use JSON where possible to remove customization text from HTML and move it to external JSON file. This will make customization easier for shop owner
## Build exact final shop
- We pick one shop first, either Bobby or Nino's shop
- They provide customization content, we put it in
- We put in exactly all products to be sold, exactly the final implementation
- Each product is < 1 USD, so it is affordable to test everything including payments
- Each product has a different exact value for testing precision, such as $0.91, $0.92, etc 
## Use Screen Recording for Documentation

Whenever we customize the shop, we make a screen recording and publish it into the playlist: "Build your own eShop". This makes it easy for the future shop owner to redo the customization.
## Clean Presentation of Liabilities
- Products sold comply with V² Standards
- Products sold are genuine parts from their respective manufacturers
- Shop owner is liable to customer, including technical support to buyer
- Village Tronic is liable to Shop Owner for its products, including technical support to shop
#5) Deployment and Maintenance
## Deployment
- Very straight forward process
- Follow our screen casts
## Maintenance
- Village Tronic uses the exact same solution 
#6) Shop Owner starts sales on his own shop

Time to serve the community and make some money in the process.
# Tasks
- [x] HC: Discuss with Bobby if he wants to go this way → Yes
- [x] HC: Write initial Article
- [ ] @bcaswelch Provide feedback
- [ ] Nino: Provide feedback

**Comment by bcaswelch** [comment]
Sounds great! Is the shop layout going to be similar with how you have the new homepage?

**Comment by VillageHubertChen** [comment]
We do not know yet. It may be possible. We need to choose between two technologies:

Current shop technology:
- Based on Joomla
- layout are based on Joomla Plugins and Joomla Templates
- Virtue Mart shop is shop extensin to Joomla
- It is already working
- compatibility testing on different OS and browsers is not possible
- developing is hard work and slow

New technology we are considering
- web site is hand coded (it now looks this is faster as in joomla and more freedom)
- Shop: We will need to pick a new shop (testing will take time, we do not know what we will get)
- testing on different browsers and OS is easy ( we do it now already)
- development is much faster
- complete freedom in layout. We can do exactly as we do now.

We will look into making this decision, after we finish the V² pages enough, so they can be used by others to start contributing.
