### ISSUE TITLE
ViPC Shop in Custom Store Platform

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#8]
# Introduction

Our opriginal plan was that in the beginning we would only sell by opening V² Community Shops in Major Store Platforms, such as Amazon, eBay, Newegg, Taoabo, etc ... While this continues to work for selling ViCase, we found that there is the problem of negative cashflow for ViPC -> #1 which we developed several solutions for in -> #5. Opening a V² Community Shop in a custom Store Platform is one such solution, which we will be discussing here in detail.
# Executive Summary Proposal

Lets do both right from the start: Amazon Shop and Custom Platform Shop. Both help each other. The proposed Project Plan limits financing cash flow to one ViPC. With this limited investment it opens up much more sales.
# Synergies of selling in both platforms
## Please more customers

Customers are different. Some will trust buying a product in a custom platform shop more. Some will trust more to buy a product in a Major Store Platform. Some will appreciate the added shopping experience in the Custom Store, where we provide ViPC Web Apps, which gives them a shopping experience very close to walk into a real store and hold a real ViCase in hand.
### Amazon as in paid advertisement

Some customers search in Amazon what kind of products are available, yet they will buy in other places, expectingh better deals outside amazon. Buy selling even small quantities in amazon these customers can find ViCase as a product type they want and then they will search for a shop to sell it and will find the ViPC shop in the Custom Platform.
### Amazon as in paid insurance for customer

Some customers only buy on Amazon as they want to enjoy its customer protection. They accept it is more expensive there, but the addes safety and the reduce struggles with the shops is worth it to them. So even if a buyer find's ViPC in your Custom Platform Shop first, he might appreciate the link to the alternative Amazon Shop and eventually buy there.
# Major Store Platform vs Custom Store Platform
## ViPC in Major Shop Platform
- **Buyer's PLUS:**
  - ViPC is easier to be found for customer in Amazon Shop. But you pay for it with Referral Fees.
  - ViPC is easier to compare to competing offerings by the customer in Amazon Shop
  - Easier to trust the reviews, as the shop owner can not edit or fake them
  - More buyer protection, provided by protection mechanisms of Major Store Platform
- **Buyer's MINUS:**
  - Experiencing the products through our web apps is not possible (no web apps allowed)
  - Configuring ViPC with V²Configurator is not possible (no web apps allowed)
  - Shop experience is limited to pattern of major online shop
  - ViPC is higher price (Major Platform adds about 10% more costs)
  - No links to ViPC and V²PC site. He needs to find them by himself
  - No Videos, that can explain the product conveniently
    - UPDATE: Bobby has seen Videos in Amazon Product pages
- **Seller's PLUS:**
  - No need to set up server and eCommerce platform
  - ViPC is easier to be found by customer leads to more sales with same marketing efforts
- **Seller's MINUS:**
  - Seller need credit line or cash to finance negative cash flow -> #1
## ViPC in Custom Shop Platform
- **Buyer's PLUS:**
  - Easier to be found when searching in Google due to Adwords
  - ViPC is lower price
  - Shopping experience is much richer due to ViPC Apps
  - Customization of ViPC is much easier due to V²Configurator
  - All in all richer shopping experience, as we can do a lot with full custom programming
  - Lots of references to ViPC and V²PC pages makes researching faster and more convenient
  - Embedded Videos will give the buyer very good ideas on what to expect
- **Buyer's MINUS:**
  - Less buyer protection. It can be helped:
    - Gained reputation if the Shop Owner is also member of the V²Board
    - Video about assembly and test process, showing shop owner diligently at work
    - Link to same offer in Amazon. They can see some are sold there with good reviews
      - Some people will come back to Personal shop, as Amazon offer is
        - More expensive
        - Sometimes out of stock, when the one PC cash flow is used up. Still can pre-order
    - Add mediation level of Village Tronic to mediate between Shop and Buyer
  - Reviews may not be so trusted. Shop owner has full control in shop reviews. Can be helped
    - Add reviews of V²Community Shop in ViSite
- **Seller's PLUS:**
  - No need for credit line. Positive cash-flow through whole process
  - Much more options to express yourself, including adding Videos about yourself and your store
- **Seller's MINUS:**
  - Work harder for products to be found. It can be helped:
    - Google Adwords
    - References from V²Site, ViSite 
  - Harder to be trusted. It can be helped a bit:
    - Reviews on ViSite of V²Community Shops
  - Need to set up server and eCommerce system. Complexity can be helped:
    - We can develop and share on GitHub an online shop template
    - Service and cost: sign up for $1 / month hoster. Basic features: HTML, CSS, JS and PHP
    - Work: Follow our tutorials to copy files, then customize them
    - Shop experience can be rich. We can do what we want and we are getting skillful!
    - Improvements and bug fixing can be done on shop template in V²GitHub
    - more information → #7 
# Proposed Project Plan
1. Open Amazon Shop now in USA and Germany
2. Prepare selling ViCase with no limitations in Amazon
3. Also prepare selling ViPC in Amazon. But always limit qty to 1 piece. After sales occurs, set availability to 0. After Amazon releases funds, set availability to 1 again. This way your exposure is limited. When customer buys, you can make agrement with him that he can not return the ViPC, as it is custom purchased and custom build for him.
4. In parallel we will build a Template for a Custom Store Platform. This will allow you with relative little effort to open your own store. In this store you will have no negative cash flow problem.
5. With time your profits will accumulate and you will have more cash to finance the negative cash flow. If you run your business through credit card you can finance the cash flow through credit card.
# Tasks
- [x] HC: Discuss with Bobby if he wants to go this way → Yes
- [x] HC: Write initial Article
- [ ] @bcaswelch Provide feedback
- [ ] Nino: Provide feedback

**Comment by bcaswelch** [comment]
Like how the shops are planning to be set up. One change with the amazon shop is that there can be videos shown; I've seen a couple products that have videos embedded.

**Comment by VillageHubertChen** [comment]
Thanks. Glad you like it. The more we are working on this the more I feel this is going to work great for everybody. 

Thanks for the update on the video with amazon. I have updated the description accordingly that video is possible in amazon product page.
