### ISSUE TITLE
Selling ViCase and ViPC in Asia

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/v2-How-to-Online-Shop#9]
# Sales Channels
## eBay
- Hong Kong
- Singapore
- Malaysia
- Australia
## Newegg
- China
- Taiwan
## Taobao
- China
## Village Tronic
- Our own shop on our site
# Strategy
- We offer our products in eBay and Newegg so that customers who search in these platform find our products. It is like paid advertisement.
- Our Products in Newegg and Amazon are more expensive than in our own online shop. The platform add costs to the product. At the same time they add safety for the customers. So the customers who prefer such safety will be willing to pay for it.
- Some customers will find our products in Newegg and eBay. Then search for it in Google, find the products in our shop and buy there because it is lower cost
- Some customers will find our products in our shop. We will also link in our shop to eBay and Newegg, eBay and Taobao shops. They might prefer to buy there, even they are more expensive, due to the added safety.
- Offerings in eBay, Newegg and Taobo are limited in stock, because we have limited cash to overcome the negative cash flow problem. → #1 
- Offerings in our own shop have no limited stock. We have no negative cash flow problem there.
- Bobby is researching if on Newegg we can offer a ViPC Combo Deal. This will solve the negative cash flow problem.  More information → #3 
# Creating Win - Win for V² OEM
## Copying designs in Asia is a fact in life

It is also a force of economy. Rather than to fight it we create a Win - Win situation for both the company who copies us and for us. Who copies us is referred to as V²Case or V²PC OEM
## Win for V²PC OEM
1. The OEM can say in his marketing materials it is a German design. In many Asian countries this helps sales and is very useful to differentiate one Maker / Shop versus the competition.
2. The OEM can link to the V² Site, which shows all features and care of V² Design. It also substantiate the claim to be German Design.
3. V² License costs no money and requires no application process. In short the V²PC / ViCase OEM gets a competitive edge at no cost.
## Win for V² Initiative
- Every Case or PC sold with reference to be V² Compatible is promoting the V² Brand.
- Effect on funding V²: The source of funding is sales of ViCase Trailblazer Products. Every OEM evaluating to build a compatible V²Case or V²PC would buy ViCase Trailblazer Products, as they are also very low cost Rapid Development Kits. 
- Our high quality Aluminum ViCase is expensive to make and sales price is accordingly thus qty is small. Typical business for OEM is large quantity housing at low cost. As such we would not be competing.
# Tasks
- [x] HC: Initial meeting with XM about sales in China. Use her feedback to write this Issue
- [ ] XM: Check out Newegg China. Write a report of comparing Taobao to Newegg. 
- [ ] XM: Check if Newegg China has Combo Deals. → #3 . If they do have, post one or more links to example combo deals.
- [ ] XM: Think about the V² Strategy where it is desirable that Chinese Companies make lower cost copies of ViCase and sell them as V²Case compatible. Let HC know if you agree after sleeping over it?
- [ ] XM: Create a GitHub account. Remember to not use Google+, Facebook or others to create account, otherwise you always need to use GitHub with VPN. I registered without social media login and I can use GitHub all the time without VPN. Very convenient! Please use the login: "VillageXiaoMao" and your real name as name.
- [ ] XM: Discuss all topics / feedback with HC on Monday.

**Comment by VillageHubertChen** [comment]
# Feedback from Georg

The "Creating Win - Win for V² OEM" I talked about on skype was missing in text.
- [x] HC: add the "Creating Win - Win for V² OEM" part

**Comment by bcaswelch** [comment]
R&U. Going to have to figure out the details of setting up as a business for newegg (can't do personal shop).

**Comment by VillageHubertChen** [comment]
Yes. But for timing you need to keep in mind that we are considering to completely change the time line, see the new Road Map:
- **Q2:** Get support for V² / Build Configurations / Pre-Sales of ViCase
- **Q3:** Start V² Community stores.

If you agree this approach, all V² Community store tasks are moved to July. Please let me know if you agree.
